### ISSUE TITLE
PDFsign IE

### ISSUE THREAD

**Issue by maromp90** [Communication-Systems-Group/pdfsign.js#1]
hi,
i can´t sign a pdf with internet explorer browser, i try use a try{}catch{} but don´t return any error.
i think that is cause of pdf.js with ie.
the result of pdfsign, i try view but pdf error view.

I expect an answer, thanks.

**Comment by tbocek** [comment]
We have only tested PDFsign with FF and Chrome, please try to use a recent browser.
