### ISSUE TITLE
Sign gets added but not visible

### ISSUE THREAD

**Issue by prem911** [Communication-Systems-Group/pdfsign.js#2]
On running the sample example, a new pdf gets generated. The signature panel shows the signature but it is not visible.

**Comment by tbocek** [comment]
Right, on line 426 and 543 in src/js/main.js, we create a widget in a rectangle 0,0,0,0, meaning its not visible. Adding a signature widget, would mean to create an appropriate widget in these lines. Its not implement, as it was not a requirement for us.
